"use strict";

const path = require("node:path");
const fs = require("node:fs");
const { buildViewModel } = require("./projectQuotationDocx/viewModel");
const { documentXml, stylesXml, headerXml, footerXml } = require("./projectQuotationDocx/builders");

const DOCX_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
function sanitizeFileName(value) { return String(value || "project-quotation").replace(/[\\/:*?"<>|]+/g, "-").slice(0, 120); }

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => { let c=n; for(let k=0;k<8;k+=1)c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1); return c>>>0; });
function crc32(buffer){let crc=-1;for(let i=0;i<buffer.length;i+=1)crc=(crc>>>8)^CRC_TABLE[(crc^buffer[i])&255];return(crc^-1)>>>0;}
function dosDateTime(date=new Date()){return{time:(date.getHours()<<11)|(date.getMinutes()<<5)|Math.floor(date.getSeconds()/2),date:((Math.max(1980,date.getFullYear())-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()};}
function createZip(entries){const now=dosDateTime(),files=[],central=[];let offset=0;for(const entry of entries){const name=Buffer.from(entry.name),data=Buffer.isBuffer(entry.data)?entry.data:Buffer.from(String(entry.data),"utf8"),crc=crc32(data),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(now.time,10);local.writeUInt16LE(now.date,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(name.length,26);files.push(local,name,data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(now.time,12);c.writeUInt16LE(now.date,14);c.writeUInt32LE(crc,16);c.writeUInt32LE(data.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(offset,42);central.push(c,name);offset+=local.length+name.length+data.length;}const size=central.reduce((s,p)=>s+p.length,0),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(size,12);end.writeUInt32LE(offset,16);return Buffer.concat([...files,...central,end]);}

function contentTypesXml(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/fontTable.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>`;}
function rootRelsXml(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;}
function wordRelsXml(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdHeader" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rIdFooter" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rIdFonts" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/><Relationship Id="rIdLogo" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/lds-logo.png"/></Relationships>`;}
function fontTableXml(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:fonts xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:font w:name="Heiti SC"><w:altName w:val="Microsoft YaHei"/><w:family w:val="swiss"/><w:charset w:val="86"/></w:font><w:font w:name="Arial"><w:family w:val="swiss"/><w:charset w:val="00"/></w:font></w:fonts>`;}
function buildProjectQuotationDocx(quote,options={}){if(!quote||typeof quote!=="object")throw new Error("Quote is required.");const vm=buildViewModel(quote,options);const logo=fs.readFileSync(path.join(__dirname,"../assets/lds-logo.png"));return createZip([{name:"[Content_Types].xml",data:contentTypesXml()},{name:"_rels/.rels",data:rootRelsXml()},{name:"word/_rels/document.xml.rels",data:wordRelsXml()},{name:"word/styles.xml",data:stylesXml()},{name:"word/fontTable.xml",data:fontTableXml()},{name:"word/header1.xml",data:headerXml(vm)},{name:"word/footer1.xml",data:footerXml(vm)},{name:"word/media/lds-logo.png",data:logo},{name:"word/document.xml",data:documentXml(vm)}]);}
function projectQuotationDocxFileName(quote){const base=quote&&(quote.quoteNumber||quote.id)?`project-quotation-${quote.quoteNumber||quote.id}`:"project-quotation";return sanitizeFileName(path.basename(base))+".docx";}
module.exports={DOCX_CONTENT_TYPE,buildProjectQuotationDocx,projectQuotationDocxFileName};
