(() => {
  const headers=()=>({Authorization:`Bearer ${window.AuthStore?.getToken()||''}`,'Content-Type':'application/json'}),form=document.querySelector('#adv-form'),itemsEl=document.querySelector('#adv-items'),groupsEl=document.querySelector('#adv-groups'),params=new URLSearchParams(location.search);let catalog,quote={},groups=[],timer;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  form.elements.mode.value=params.get('mode')||'standard';
  const uid=prefix=>`${prefix}-${crypto.randomUUID()}`;
  const renderGroupOptions=selected=>`<option value="">未分组</option>${groups.map(g=>`<option value="${esc(g.id)}" ${g.id===selected?'selected':''}>${esc(g.nameZh)}</option>`).join('')}`;
  function renderGroups(){document.querySelector('#adv-groups-panel').classList.toggle('hidden',form.elements.mode.value!=='project');groupsEl.innerHTML=groups.map((g,i)=>`<article class="advertising-group" data-group-id="${esc(g.id)}"><header class="adv-group-head"><div><span>分组 ${i+1}</span><strong>${esc(g.nameZh||'未命名分组')}</strong></div><p>分组小计 <strong data-group-subtotal>0.00 EUR</strong></p></header><div class="advertising-grid adv-group-fields"><label>分组名称<input data-gkey="nameZh" value="${esc(g.nameZh||'')}"></label><label>英文名称<input data-gkey="nameEn" value="${esc(g.nameEn||'')}"></label><label>说明<input data-gkey="notes" value="${esc(g.notes||'')}"></label></div><div class="adv-inline-actions"><button type="button" data-up ${i===0?'disabled':''}>上移</button><button type="button" data-down ${i===groups.length-1?'disabled':''}>下移</button><button class="adv-danger-action" type="button" data-delete>删除分组</button></div></article>`).join('');groupsEl.querySelectorAll('.advertising-group').forEach((row,i)=>{row.oninput=()=>{const g=groups[i];row.querySelectorAll('[data-gkey]').forEach(x=>g[x.dataset.gkey]=x.value);row.querySelector('.adv-group-head strong').textContent=g.nameZh||'未命名分组';refreshItemGroupOptions();preview()};row.querySelector('[data-up]').onclick=()=>moveGroup(i,-1);row.querySelector('[data-down]').onclick=()=>moveGroup(i,1);row.querySelector('[data-delete]').onclick=()=>{if(confirm('删除分组后，产品将变为未分组。')){const id=groups[i].id;groups.splice(i,1);itemsEl.querySelectorAll('[data-key=groupId]').forEach(x=>{if(x.value===id)x.value=''});renderGroups();refreshItemGroupOptions();preview()}}});}
  function moveGroup(i,delta){const target=i+delta;[groups[i],groups[target]]=[groups[target],groups[i]];renderGroups();refreshItemGroupOptions();preview()}
  function refreshItemGroupOptions(){itemsEl.querySelectorAll('[data-key=groupId]').forEach(select=>{const value=select.value;select.innerHTML=renderGroupOptions(value);select.value=value})}
  function refreshItemOrder(){const rows=[...itemsEl.querySelectorAll('.advertising-item')];rows.forEach((row,index)=>{row.querySelector('.adv-item-head span').textContent=`产品 ${index+1}`;const up=row.querySelector('[data-up]'),down=row.querySelector('[data-down]'),remove=row.querySelector('[data-remove]');up.disabled=index===0;down.disabled=index===rows.length-1;up.setAttribute('aria-label',`上移产品 ${index+1}`);down.setAttribute('aria-label',`下移产品 ${index+1}`);remove.setAttribute('aria-label',`删除产品 ${index+1}`)})}
  function itemTemplate(item={}){const row=document.createElement('article');row.className='advertising-item';row.dataset.itemId=item.id||uid('ADI');const itemNumber=itemsEl.children.length+1;row.innerHTML=`<header class="adv-item-head"><div><span>产品 ${itemNumber}</span><h3 data-item-heading>${esc(item.name||'未命名产品')}</h3></div><div class="adv-inline-actions"><button type="button" data-up>上移</button><button type="button" data-down>下移</button><button class="adv-danger-action" type="button" data-remove>删除</button></div></header><div class="advertising-grid adv-item-fields"><label class="adv-field-group">项目分组<select data-key="groupId">${renderGroupOptions(item.groupId)}</select></label><label class="adv-field-name">产品名称<input data-key="name" value="${esc(item.name||'')}" required placeholder="例如：门店 PVC 展板"></label><label class="adv-field-name-en">英文名称<input data-key="nameEn" value="${esc(item.nameEn||'')}" placeholder="Optional"></label><label class="adv-field-material">材料<select data-key="materialId">${catalog.materials.map(x=>`<option value="${esc(x.id)}" ${x.id===item.materialId?'selected':''}>${esc(x.nameZh)} · ${esc(x.specification)}</option>`).join('')}</select></label><label>宽度<input data-key="width" type="number" min="1" value="${esc(item.width||1000)}"></label><label>高度<input data-key="height" type="number" min="1" value="${esc(item.height||1000)}"></label><label>尺寸单位<select data-key="sizeUnit"><option>mm</option><option>cm</option><option>m</option></select></label><label>数量<input data-key="quantity" type="number" min="1" value="${esc(item.quantity||1)}"></label><label>面数<select data-key="sides"><option value="1">单面</option><option value="2">双面</option></select></label><fieldset class="adv-process-panel" data-processes><legend>加工工艺 <span>可多选</span></legend></fieldset><label>材料销售价覆盖<input data-key="materialSaleUnitPrice" type="number" min="0" step="0.01" value="${esc(item.materialSaleUnitPrice??'')}" placeholder="使用建议价"></label><label>手工调整<input data-key="manualAdjustment" type="number" step="0.01" value="${esc(item.manualAdjustment||0)}"></label><label class="adv-field-notes">备注<input data-key="notes" value="${esc(item.notes||'')}" placeholder="制作、安装或交付说明"></label></div>`;
    const material=row.querySelector('[data-key=materialId]'),box=row.querySelector('[data-processes]');const sync=()=>{const selected=new Map((item.processes||[]).map(x=>[x.processId,x]));const ids=catalog.rules.filter(x=>x.materialId===material.value&&x.isActive!==false).map(x=>x.processId);const available=catalog.processes.filter(x=>ids.includes(x.id));box.innerHTML='<legend>加工工艺 <span>可多选</span></legend>'+(available.length?'<div class="adv-process-options">'+available.map(x=>`<label><input type="checkbox" data-process-id="${esc(x.id)}" ${selected.has(x.id)?'checked':''}><span>${esc(x.nameZh)}</span>${x.requiresManualQuote?`<input class="${selected.has(x.id)?'':'hidden'}" type="number" min="0" step="0.01" data-process-price placeholder="手工售价" value="${esc(selected.get(x.id)?.actualSalePrice??'')}" ${selected.has(x.id)?'':'disabled'} aria-label="${esc(x.nameZh)}手工售价">`:''}</label>`).join('')+'</div>':'<p class="adv-process-empty">当前材料暂无可用工艺</p>');box.querySelectorAll('[data-process-id]').forEach(control=>{control.addEventListener('change',()=>{const price=control.closest('label').querySelector('[data-process-price]');if(price){price.disabled=!control.checked;price.classList.toggle('hidden',!control.checked);if(control.checked)price.focus();else price.value=''}preview()})})};material.onchange=()=>{item.processes=[];sync();preview()};row.querySelector('[data-key=sizeUnit]').value=item.sizeUnit||'mm';row.querySelector('[data-key=sides]').value=String(item.sides||1);sync();row.querySelector('[data-remove]').onclick=()=>{row.remove();refreshItemOrder();preview()};row.querySelector('[data-up]').onclick=()=>moveItem(row,-1);row.querySelector('[data-down]').onclick=()=>moveItem(row,1);row.querySelector('[data-key=name]').addEventListener('input',event=>{row.querySelector('[data-item-heading]').textContent=event.target.value||'未命名产品'});row.addEventListener('input',preview);itemsEl.append(row);refreshItemOrder()}
  function moveItem(row,delta){const sibling=delta<0?row.previousElementSibling:row.nextElementSibling;if(sibling)itemsEl.insertBefore(delta<0?row:sibling,delta<0?sibling:row);refreshItemOrder();preview()}
  function itemPayload(row,index){const get=k=>row.querySelector(`[data-key=${k}]`).value;return{id:row.dataset.itemId,groupId:get('groupId')||null,name:get('name'),nameEn:get('nameEn'),materialId:get('materialId'),width:Number(get('width')),height:Number(get('height')),sizeUnit:get('sizeUnit'),quantity:Number(get('quantity')),sides:Number(get('sides')),materialSaleUnitPrice:get('materialSaleUnitPrice')===''?undefined:Number(get('materialSaleUnitPrice')),manualAdjustment:Number(get('manualAdjustment')),notes:get('notes'),position:index,processes:[...row.querySelectorAll('[data-process-id]:checked')].map((x,i)=>{const price=x.closest('label').querySelector('[data-process-price]');return{id:uid('ADP'),processId:x.dataset.processId,position:i,...(price&&price.value!==''?{actualSalePrice:Number(price.value)}:{})}})}}
  function payload(){return{...quote,entityId:form.elements.entityId.value,clientName:form.elements.clientName.value,projectName:form.elements.projectName.value,mode:form.elements.mode.value,language:form.elements.language.value,currency:'EUR',vatMode:form.elements.vatMode.value,vatRate:20,groups:groups.map((g,i)=>({...g,position:i})),minimumProcessingFee:Number(form.elements.minimumProcessingFee.value),minimumOrderAmount:Number(form.elements.minimumOrderAmount.value),discountPercent:Number(form.elements.discountPercent.value),fixedDiscount:Number(form.elements.fixedDiscount.value),adjustment:Number(form.elements.adjustment.value),adjustmentReason:form.elements.adjustmentReason.value,items:[...document.querySelectorAll('.advertising-item')].map(itemPayload),delivery:{enabled:form.elements.deliveryEnabled.checked,quantity:Number(form.elements.deliveryQuantity.value),saleUnitPrice:Number(form.elements.deliveryPrice.value)},additionalFees:Number(form.elements.installationPrice.value)>0?[{category:'installation',name:'安装',quantity:1,saleUnitPrice:Number(form.elements.installationPrice.value)}]:[]}}
  function preview(){clearTimeout(timer);const status=document.querySelector('#adv-calc-status');status.textContent='正在重新计算…';timer=setTimeout(()=>fetch('/api/advertising/quotes/calculate',{method:'POST',headers:headers(),body:JSON.stringify(payload())}).then(async r=>{const x=await r.json();if(!r.ok||x.error)throw new Error(x.error||'金额计算失败');document.querySelector('#adv-subtotal').textContent=`${x.subtotalExcludingVat.toFixed(2)} EUR`;document.querySelector('#adv-vat').textContent=`${x.vatAmount.toFixed(2)} EUR`;document.querySelector('#adv-total').textContent=`${x.totalIncludingVat.toFixed(2)} EUR`;status.textContent='金额已更新';groupsEl.querySelectorAll('.advertising-group').forEach(row=>{const sum=x.items.filter(i=>i.groupId===row.dataset.groupId).reduce((n,i)=>n+i.saleAmount,0);row.querySelector('[data-group-subtotal]').textContent=`${sum.toFixed(2)} EUR`})}).catch(error=>{status.textContent=`计算失败：${error.message}`}),180)}
  const load=()=>Promise.all([fetch('/api/advertising/catalog',{headers:headers()}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'广告价格库加载失败。');return x}),params.get('id')?fetch(`/api/advertising/quotes/${encodeURIComponent(params.get('id'))}`,{headers:headers()}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'广告报价加载失败。');return x}):Promise.resolve({})]).then(([c,q])=>{catalog=c;quote=q;groups=q.groups||[];form.elements.entityId.innerHTML=c.entities.map(x=>`<option value="${esc(x.id)}">${esc(x.nameEn||x.nameZh||x.code)}</option>`).join('');['entityId','clientName','projectName','mode','language','vatMode','minimumProcessingFee','minimumOrderAmount','discountPercent','fixedDiscount','adjustment'].forEach(k=>{if(q[k]!==undefined)form.elements[k].value=q[k]});if(q.delivery){form.elements.deliveryEnabled.checked=q.delivery.enabled;form.elements.deliveryQuantity.value=q.delivery.quantity||1;form.elements.deliveryPrice.value=q.delivery.saleUnitPrice||150}renderGroups();(q.items?.length?q.items:[{}]).forEach(itemTemplate);preview()}).catch(error=>alert(error.message));if(window.__AUTH_READY__)load();else document.addEventListener('authReady',load,{once:true});
  document.querySelector('#adv-add-group').onclick=()=>{groups.push({id:uid('ADG'),nameZh:`分组 ${groups.length+1}`,nameEn:'',notes:''});renderGroups();refreshItemGroupOptions()};document.querySelector('#adv-add-item').onclick=()=>itemTemplate({});form.elements.mode.onchange=renderGroups;form.addEventListener('input',preview);document.querySelector('#adv-save').onclick=()=>{if(!form.reportValidity())return;const body=payload();if(quote.id&&body.adjustment!==Number(quote.adjustment||0)&&!body.adjustmentReason.trim()){alert('手工调价必须填写原因。');return}fetch(quote.id?`/api/advertising/quotes/${encodeURIComponent(quote.id)}`:'/api/advertising/quotes',{method:quote.id?'PUT':'POST',headers:headers(),body:JSON.stringify(body)}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);quote=x;history.replaceState(null,'',`?id=${encodeURIComponent(x.id)}`);alert(`已保存 ${x.quoteNumber}`)}).catch(e=>alert(e.message))};
  function printQuote(internal=false){
    if(!quote.id){alert('请先保存报价。');return}
    const calculation=quote.calculationSnapshot||{};
    const visible=(quote.items||[]).filter(item=>item.customerVisible!==false);
    const rows=visible.map(item=>{const calculated=(calculation.items||[]).find(entry=>entry.id===item.id)||item;return{name:item.name||'广告产品',quantity:item.quantity||1,amount:Number(calculated.saleAmount||0),cost:internal?Number(calculated.costAmount||0):null}});
    for(const fee of (calculation.additionalFees||[]).filter(entry=>entry.customerVisible!==false&&entry.category!=='delivery'))rows.push({name:fee.nameZh||fee.name||fee.category||'附加服务',quantity:fee.quantity||1,amount:Number(fee.saleAmount||0),cost:internal?Number(fee.costAmount||0):null});
    const summary=[['最低订单补差',calculation.minimumOrderSurcharge],['配送费',calculation.deliverySale],['加急费',calculation.urgentSale],['折扣',-Number(calculation.discountAmount||0)],['整单调整',calculation.adjustment],['VAT',calculation.vatAmount]];
    for(const [name,value] of summary){const amount=Number(value||0);if(Math.abs(amount)>0.0001)rows.push({name,quantity:1,amount,cost:null})}
    const total=Number(calculation.totalIncludingVat??calculation.subtotalExcludingVat??0);
    const detail=rows.reduce((sum,row)=>sum+row.amount,0);
    const difference=Number((total-detail).toFixed(2));
    if(Math.abs(difference)>0.0001)rows.push({name:'其他已计入金额',quantity:1,amount:difference,cost:null});
    const company=quote.entitySnapshot||{};
    const popup=window.open('about:blank','_blank');
    if(!popup){alert('浏览器阻止了打印窗口，请允许弹窗后重试。');return}
    popup.opener=null;
    const rowHtml=rows.map(row=>`<tr><td>${esc(row.name)}</td><td>${esc(row.quantity)}</td>${internal?`<td>${row.cost===null?'—':Number(row.cost).toFixed(2)}</td>`:''}<td>${Number(row.amount).toFixed(2)}</td></tr>`).join('');
    popup.document.write(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>${esc(quote.quoteNumber||'广告报价')}</title><style>@page{size:A4;margin:15mm}body{font-family:Arial,"PingFang SC",sans-serif;color:#172033}header{border-bottom:2px solid #193b63;margin-bottom:24px}h1{font-size:26px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccd5df;padding:8px;text-align:left}th{background:#edf3f8}.total{text-align:right;font-size:22px;font-weight:700;margin-top:20px}.internal{color:#a33;font-weight:700}@media print{button{display:none}}</style></head><body><header><strong>${esc(company.nameEn||company.nameZh||company.code||'')}</strong>${internal?'<p class="internal">内部核算版 / INTERNAL USE ONLY</p>':''}<h1>广告制作报价 / Advertising Production Quotation</h1><p>编号：${esc(quote.quoteNumber||'')}　客户：${esc(quote.clientName||'')}　项目：${esc(quote.projectName||'')}</p></header><table><thead><tr><th>项目</th><th>数量</th>${internal?'<th>成本</th>':''}<th>金额 (${esc(quote.currency||'EUR')})</th></tr></thead><tbody>${rowHtml}</tbody></table><p class="total">总计：${esc(quote.currency||'EUR')} ${total.toFixed(2)}</p><button onclick="window.print()">打印 / 保存为 PDF</button><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),250))<\/script></body></html>`);
    popup.document.close();
  }
  async function download(format,internal=false){if(format==='pdf'){printQuote(internal);return}if(!quote.id){alert('请先保存报价。');return}const r=await fetch(`/api/advertising/quotes/${encodeURIComponent(quote.id)}/export/${format}${internal?'?internal=1':''}`,{method:'POST',headers:headers()});if(!r.ok){const x=await r.json();alert(x.error);return}const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.headers.get('content-disposition')?.match(/filename="([^"]+)"/)||[])[1]||`${quote.quoteNumber}.${format==='docx'?'docx':'pdf'}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}document.querySelector('#adv-export-docx').onclick=()=>download('docx');document.querySelector('#adv-export-pdf').onclick=()=>download('pdf');document.querySelector('#adv-export-internal-docx').onclick=()=>download('docx',true);document.querySelector('#adv-export-internal-pdf').onclick=()=>download('pdf',true);const revealInternalExports=()=>{if(window.can('advertising_quote.cost_view')){document.querySelector('#adv-export-internal-docx').classList.remove('hidden');document.querySelector('#adv-export-internal-pdf').classList.remove('hidden')}};if(window.__AUTH_READY__)revealInternalExports();else document.addEventListener('authReady',revealInternalExports,{once:true});
})();
